version: '2.4'
services:
  api:
    image: iker0610/as-client-api
    ports:
      - "80:80"
    depends_on:
      memcached:
        condition: service_healthy

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    healthcheck:
      test: echo stats | nc memcached 11211
      interval: 10s
      retries: 60
