apiVersion: v1
kind: Service
metadata:
  name: memcached-db-service
  labels:
    app: memcached
    role: db
spec:
  type: ClusterIP
  selector:
    app: memcached
    role: db
  ports:
    - port: 11211
      targetPort: 11211

---

apiVersion: v1
kind: Service
metadata:
  name: memcached-db-service
  labels:
    app: memcached
    role: db
spec:
  type: ClusterIP
  selector:
    app: memcached
    role: db
  ports:
    - port: 11211

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-db
  labels:
    app: memcached
    role: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
        role: db
    spec:
      containers:
        - name: memcached
          image: memcached:alpine
          ports:
            - containerPort: 11211
