version: "3.9"
services:
  api:
    image: iker0610/as-client-api
    environment:
      - MEMCACHED_IP=memcached
    ports:
      - "8080:80"
    volumes:
      # Volume
      - type: volume
        source: backup
        target: /client_api/backup

      # Bind Mount
      #- type: bind
      #  source: ./backup
      #  target: /client_api/backup

    depends_on:
      memcached:
        condition: service_healthy

  memcached:
    image: memcached:alpine
    expose:
      - "11211"
    healthcheck:
      test: echo stats | nc memcached 11211
      interval: 10s

volumes:
  backup: